services:
  # Backend Service
  - type: web
    name: crustdata-support-chat
    env: python
    buildCommand: |
      pip install -r requirements.txt
      npm install
      npm run build
      cp -r build ./build
    startCommand: gunicorn app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: NODE_VERSION
        value: 18.0.0
    plan: free
    branch: main
    healthCheckPath: /health
    autoDeploy: true