services:
  # Backend Service
  - type: web
    name: crustdata-support-chat-backend
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app --config gunicorn.conf.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: PORT
        value: 10000
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: free
    branch: main
    healthCheckPath: /health
    autoDeploy: true

  # Frontend Service
  - type: web
    name: crustdata-support-chat-frontend
    env: node
    buildCommand: |
      npm ci
      npm run build
    startCommand: npx serve -s build -l $PORT
    envVars:
      - key: REACT_APP_API_URL
        value: https://crustdata-support-chat-backend.onrender.com
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
    plan: free
    branch: main
    autoDeploy: true